apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingpong-ingress
  namespace: app-space
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /pingpong
        backend:
          service:
            name: pingpong-svc
            port:
              number: 2345